# csv: "/data/temporary/clement/code/slide2vec/data/debug.csv"
csv: "/data/temporary/clement/code/slide2vec/data/debug-leopard.csv"

output_dir: "output/debug"
resume: false
resume_dirname:

visualize: true

seed: 0

tiling:
  read_coordinates_from:
  backend: "asap"
  params:
    spacing: 0.5
    tolerance: 0.1
    tile_size: 224
    overlap: 0.0
    tissue_thresh: 0.05
    drop_holes: false
    use_padding: true
  seg_params:
    downsample: 64
    sthresh: 8
    sthresh_up: 255
    mthresh: 7
    close: 4
    use_otsu: false
    tissue_pixel_value: 1
  filter_params:
    ref_tile_size: 224
    a_t: 4
    a_h: 2
    max_n_holes: 8

model:
  level: "tile"
  name: "uni"
  arch:
  pretrained_weights:
  batch_size: 1
  tile_size: ${tiling.params.tile_size}
  patch_size: 256

speed:
  fp16: false
  num_workers_tiling: 8
  num_workers_embedding: 8

wandb:
  enable: false
  project:
  username:
  exp_name:
  tags: ["features", "${model.level}", "${tiling.params.tile_size}"]
  dir: "/home/user/"
  group:
  resume_id: "${resume_dirname}"